// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pixnanztazgzrtwzdpfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeG5hbnp0YXpnenJ0d3pkcGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODM2ODcsImV4cCI6MjA1OTc1OTY4N30.qN0cR1QNLGm5-LUdWdLDaCgK4qOA6Z59KhxfqIToay0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);